apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment1
  namespace: default
  labels:
    app.kubernetes.io/name: demo-pods
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-pods
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-pods
    spec:
      containers:
      - name: demo
        image: elmendez/busyhttp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccountName: default

---
# k8s/service.yaml - Para exponer tu aplicación
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
  labels:
    app.kubernetes.io/name: demo-pods
spec:
  selector:
    app.kubernetes.io/name: demo-pods
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP