apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
  labels:
    app.kubernetes.io/name: demo-pods
spec:
  selector:
    app.kubernetes.io/name: demo-pods
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP